const jCategory = [
    {
        index: 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "01",
        hours: "50h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from home",
        education: "Bachelor degree in any Computer Science Course.",
        experience: "2 to 5 year(s)",
    },
    {
        index: 1,
        image: "../images/uber.png",
        title: "Freelancer",
        rate: "$900-1200/m",
        av: "Freelancer",
        companyName: "uber",
        location: "USA",
        vacancy: "04",
        hours: "40h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from office",
        education: "Degree in any Computer Science Course.",
        experience: "1 to 5 year(s)",
    },
     {
        index: 2,
        image: "../images/linkedin.png",
        title: "Business Associate",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Linkedin",
        location: "USA",
        vacancy: "11",
        hours: "40h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from office",
        education: "Degree in any Computer Science Course.",
        experience: "1 to 5 year(s)",
    },
     {
        index: 3,
        image: "../images/apple.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Apple",
        location: "USA",
        vacancy: "02",
        hours: "50h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from office",
        education: "Bachelor degree in any Computer Science Course.",
        experience: "1 to 5 year(s)",
    },
     {
        index: 4,
        image: "../images/wordpress.png",
        title: "Freelancer",
        rate: "$900-1200/m",
        av: "Freelancer",
        companyName: "Wordpress",
        location: "USA",
        vacancy: "07",
        hours: "50h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from home",
        education: "Degree in any Computer Science Course.",
        experience: "3 to 5 year(s)",
    },
     {
        index: 5,
        image: "../images/instagram.png",
        title: "Product Designer",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Instagram",
        location: "USA",
        vacancy: "04",
        hours: "50h / Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here', making it look like readable English.",
        workplace: "Work from home",
        education: "Degree in any Computer Science Course.",
        experience: "3 to 5 year(s)",
    },
];
